### ISSUE TITLE
Error when trying to add new user to organization

### ISSUE THREAD

**Issue by rafael-appsimples** [kactus-io/website#15]
I'm trying to add a new user to my organisation through the website (in this page: https://kactus.io/org/) but I'm receiving a generic error in the interface ( [Object object]). 

When inspecting the network I saw that the request https://api.kactus.io/v1/orgs/member returned a code 500 with the error:
{"message":"User: arn:aws:sts::305828152753:assumed-role/kactus-api-production-eu-west-1-lambdaRole/kactus-api-production-addMemberToOrg is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-west-1:305828152753:table/production-dynamo-kactus-users/index/indexByLogin"}

Can you guys help?

**Comment by mathieudutour** [comment]
should work now, could you try again? Sorry for the inconvenience

**Comment by rafael-appsimples** [comment]
Done, thank you for the fast support!
