### ISSUE TITLE
Can't create organization

### ISSUE THREAD

**Issue by XenorPLxx** [kactus-io/website#16]
Hello!
I wanted to create an organization for my company, but after adding a credit card it went back to the site and there was only 'Object object' error in the top right, but the organization was not created.

It seems like the site is still using old, pre-PSD2 Stripe form. The new SCA form can be implemented following the migration guide here https://stripe.com/docs/billing/migration/strong-customer-authentication.

For now, we just use personal accounts, but we'd like to centralize user & payment management.

**Comment by mathieudutour** [comment]
I pushed a big update to the website. I'm not sure what was the error but it's probably not because of SCA (since I did update it).
