### ISSUE TITLE
Add markdown-it-anchor plugin to ugly-build

### ISSUE THREAD

**Issue by alampros** [kactus-io/website#3]
Add [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor) plugin to `ugly-build`'s markdown-it instance to generate linkable anchors (e.g., direct link to terms on the glossary page).

I can't find the repo for `ugly-build`, otherwise I'd submit a PR. 🤷‍♂️  Sorry!

**Comment by mathieudutour** [comment]
done. I published `ugly-build` but it's super rough, (ugly as the name implies): https://github.com/mathieudutour/ugly-build
