### ISSUE TITLE
Can't make a commit since release 0.3.0

### ISSUE THREAD

**Issue by hungrysquirrel** [kactus-io/website#8]
@mathieudutour I can't commit my latest changes since 0.3.0 update. The input field is unresponsive. The app wakes up, shows refresh icon then my change count bumps up a little, then I scroll the changed files list and again the app refresh icon appears and my change count bumps a little more. This continues for 30-60 minutes but I never get to a point where I can make a commit.

**Comment by mathieudutour** [comment]
is sketch doing something in the background perhaps? it's weird that more changes are appearing

**Comment by hungrysquirrel** [comment]
@mathieudutour I didn't have Sketch open. My workflow is to quit Sketch before I run Kactus to keep my computer happy 😄 

I had to make the commit via terminal so I could get back to work. 
Maybe it's due to generating the image previews? Is there an option to turn those off and trigger them when needed? Again just a wild guess. I don't know anything about the inner-workings of your app ;)

**Comment by mathieudutour** [comment]
the previews are only generated when you select the changes.

if it happens again, could you look at the logs?

**Comment by hungrysquirrel** [comment]
@mathieudutour Ok will do. 
Another aspect that I have seen often is that Kactus reports "x" changed files then I make a commit and either wait or restart the app without making any changes to my sketch repo and suddenly I see another "x" changed files changed.

**Comment by hungrysquirrel** [comment]
@mathieudutour Logs from today.
[2017-11-16.kactus.production.log.zip](https://github.com/kactus-io/website/files/1479866/2017-11-16.kactus.production.log.zip)

**Comment by mathieudutour** [comment]
what kind of files are changed? if it's text layers, it's a known issue: https://github.com/kactus-io/kactus/issues/60

**Comment by hungrysquirrel** [comment]
OK...Definitely lots of text layer changes!
Thanks for your quick responses. I'll close the issue since some/all of this issue is likely covered here kactus-io/kactus#60
